parameters:
  environment: ''
  backendArg: ''
  azureSubscription: ''
  rootFolder: ''
  artifactName: 'plan'
  pool: 
    vmImage: 'ubuntu-latest'
jobs:
- deployment: apply
  displayName: Terraform Apply
  pool: ${{ parameters.pool }}
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - download: current
          artifact: ${{ parameters.artifactName }}
        - template: get-tf-credentials.steps.yml
          parameters:
            azureSubscription: ${{ parameters.azureSubscription }}
        - script: |
            terraform init -input=false ${{ parameters.backendArg }}
            terraform apply -input=false -auto-approve $(Pipeline.Workspace)/${{ parameters.artifactName }}/out.plan
          displayName: Terraform Apply
          workingDirectory: ${{ parameters.rootFolder }}